-- ============================================================
-- EDUTALLER - BASE DE DATOS POSTGRESQL
-- ============================================================
-- Proyecto: EduTaller
-- SGBD: PostgreSQL
-- ============================================================

CREATE DATABASE EduTaller;

-- ============================================================
-- 1. USUARIO
-- ============================================================

CREATE TABLE Usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL DEFAULT 'alumno',
    telefono VARCHAR(9) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP,

    CONSTRAINT chk_usuario_rol
        CHECK (rol IN ('alumno', 'docente', 'administrador')),

    CONSTRAINT chk_usuario_telefono
        CHECK (telefono ~ '^[0-9]{9}$')
);

-- ============================================================
-- 2. ALUMNO
-- ============================================================

CREATE TABLE Alumno (
    id_usuario INTEGER PRIMARY KEY,

    CONSTRAINT fk_alumno_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE CASCADE
);

-- ============================================================
-- 3. DOCENTE
-- ============================================================

CREATE TABLE Docente (
    id_docente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion VARCHAR(150) NOT NULL,
    id_usuario INTEGER NOT NULL UNIQUE,

    CONSTRAINT fk_docente_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE CASCADE
);

-- ============================================================
-- 4. ADMINISTRADOR
-- ============================================================

CREATE TABLE Administrador (
    id_usuario INTEGER PRIMARY KEY,

    CONSTRAINT fk_administrador_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE CASCADE
);

-- ============================================================
-- 5. CARGA MASIVA DE ALUMNOS
-- ============================================================

CREATE TABLE CargaAlumno (
    id_carga INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_archivo VARCHAR(255) NOT NULL,
    fecha_carga TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',

    CONSTRAINT chk_carga_alumno_estado
        CHECK (
            estado IN (
                'pendiente',
                'procesando',
                'procesado',
                'error'
            )
        )
);

-- ============================================================
-- 6. DETALLE DE CARGA DE ALUMNOS
-- ============================================================

CREATE TABLE DetalleCargaAlumno (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carga INTEGER NOT NULL,
    id_usuario INTEGER NULL,

    nombre VARCHAR(150),
    correo VARCHAR(150),
    telefono VARCHAR(9),
    contrasena VARCHAR(255),

    estado VARCHAR(50) NOT NULL,

    CONSTRAINT fk_detalle_carga
        FOREIGN KEY (id_carga)
        REFERENCES CargaAlumno(id_carga)
        ON DELETE CASCADE,

    CONSTRAINT fk_detalle_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE SET NULL,

    CONSTRAINT chk_detalle_carga_estado
        CHECK (
            estado IN (
                'valido_para_registrar',
                'correo_existente',
                'datos_incompletos_o_invalidos',
                'correo_duplicado_excel',
                'creado_exitosamente'
            )
        )
);

-- ============================================================
-- 7. TIPO DE EVENTO
-- ============================================================

CREATE TABLE TipoEvento (
    id_tipo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

-- ============================================================
-- 8. TIPO DE AREA
-- ============================================================

CREATE TABLE TipoArea (
    id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

-- ============================================================
-- 9. TALLER
-- ============================================================

CREATE TABLE Taller (
    id_taller INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    ubicacion VARCHAR(255) NOT NULL,
    capacidad INTEGER NOT NULL DEFAULT 30,
    inscritos INTEGER NOT NULL DEFAULT 0,
    modalidad VARCHAR(30) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    archivado BOOLEAN NOT NULL DEFAULT FALSE,
    latitud NUMERIC(10,7),
    longitud NUMERIC(10,7),
    institucion VARCHAR(150) NOT NULL,
    imagen_url VARCHAR(500),
    id_area INTEGER NOT NULL,
    id_tipo INTEGER NOT NULL,
    id_docente INTEGER NOT NULL,

    CONSTRAINT fk_taller_area
        FOREIGN KEY (id_area)
        REFERENCES TipoArea(id_area)
        ON DELETE RESTRICT,

    CONSTRAINT fk_taller_tipo
        FOREIGN KEY (id_tipo)
        REFERENCES TipoEvento(id_tipo)
        ON DELETE RESTRICT,

    CONSTRAINT fk_taller_docente
        FOREIGN KEY (id_docente)
        REFERENCES Docente(id_docente)
        ON DELETE RESTRICT,

    CONSTRAINT chk_taller_capacidad
        CHECK (capacidad > 0 AND capacidad <= 30),

    CONSTRAINT chk_taller_inscritos
        CHECK (inscritos >= 0 AND inscritos <= capacidad),

    CONSTRAINT chk_taller_latitud
        CHECK (latitud IS NULL OR latitud BETWEEN -90 AND 90),

    CONSTRAINT chk_taller_longitud
        CHECK (longitud IS NULL OR longitud BETWEEN -180 AND 180)
);

-- ============================================================
-- 10. TALLER REQUISITO
-- ============================================================

CREATE TABLE TallerRequisito (
    id_requisito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_taller INTEGER NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    orden INTEGER NOT NULL,

    CONSTRAINT fk_requisito_taller
        FOREIGN KEY (id_taller)
        REFERENCES Taller(id_taller)
        ON DELETE CASCADE,

    CONSTRAINT chk_requisito_orden
        CHECK (orden > 0),

    CONSTRAINT uq_requisito_orden
        UNIQUE (id_taller, orden)
);

-- ============================================================
-- 11. SESION
-- ============================================================

CREATE TABLE Sesion (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_taller INTEGER NOT NULL,
    numero_sesion INTEGER NOT NULL,
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    titulo VARCHAR(150),

    CONSTRAINT fk_sesion_taller
        FOREIGN KEY (id_taller)
        REFERENCES Taller(id_taller)
        ON DELETE CASCADE,

    CONSTRAINT chk_sesion_numero
        CHECK (numero_sesion > 0),

    CONSTRAINT chk_sesion_horas
        CHECK (hora_fin > hora_inicio),

    CONSTRAINT uq_sesion_numero
        UNIQUE (id_taller, numero_sesion)
);

-- ============================================================
-- 12. RECURSO
-- ============================================================

CREATE TABLE Recurso (
    id_recurso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion INTEGER NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    descripcion VARCHAR(300),
    archivo_url VARCHAR(500) NULL,
    enlace_url VARCHAR(500) NULL,
    fecha_subida TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_recurso_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES Sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT chk_recurso_tipo
        CHECK (tipo IN ('word', 'pdf', 'imagen'))
);

-- ============================================================
-- 13. INSCRIPCION
-- ============================================================

CREATE TABLE Inscripcion (
    id_inscripcion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inscripcion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(30) NOT NULL,
    id_alumno INTEGER NOT NULL,
    id_taller INTEGER NOT NULL,

    CONSTRAINT fk_inscripcion_alumno
        FOREIGN KEY (id_alumno)
        REFERENCES Alumno(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_inscripcion_taller
        FOREIGN KEY (id_taller)
        REFERENCES Taller(id_taller)
        ON DELETE CASCADE,

    CONSTRAINT uq_inscripcion_alumno_taller
        UNIQUE (id_alumno, id_taller)
);

-- ============================================================
-- 14. ASISTENCIA
-- ============================================================

CREATE TABLE Asistencia (
    id_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_inscripcion INTEGER NOT NULL,
    id_sesion INTEGER NOT NULL,
    asistio BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_asistencia_inscripcion
        FOREIGN KEY (id_inscripcion)
        REFERENCES Inscripcion(id_inscripcion)
        ON DELETE CASCADE,

    CONSTRAINT fk_asistencia_sesion
        FOREIGN KEY (id_sesion)
        REFERENCES Sesion(id_sesion)
        ON DELETE CASCADE,

    CONSTRAINT uq_asistencia_inscripcion_sesion
        UNIQUE (id_inscripcion, id_sesion)
);

-- ============================================================
-- 15. CONTACTO
-- ============================================================

CREATE TABLE Contacto (
    id_contacto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    asunto VARCHAR(150) NOT NULL,
    mensaje TEXT NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    leido BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_contacto_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE CASCADE
);

-- ============================================================
-- 16. MENSAJE
-- ============================================================

CREATE TABLE Mensaje (
    id_mensaje INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto VARCHAR(150) NOT NULL,
    mensaje TEXT NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    leido BOOLEAN NOT NULL DEFAULT FALSE,
    leido_por_alumno BOOLEAN NOT NULL DEFAULT FALSE,
    respondido BOOLEAN NOT NULL DEFAULT FALSE,
    id_alumno INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    id_taller INTEGER NULL,

    CONSTRAINT fk_mensaje_alumno
        FOREIGN KEY (id_alumno)
        REFERENCES Alumno(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_mensaje_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_mensaje_taller
        FOREIGN KEY (id_taller)
        REFERENCES Taller(id_taller)
        ON DELETE SET NULL
);

-- ============================================================
-- 17. RESPUESTA MENSAJE
-- ============================================================

CREATE TABLE RespuestaMensaje (
    id_respuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mensaje INTEGER NOT NULL,
    texto TEXT NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario INTEGER NOT NULL,

    CONSTRAINT fk_respuesta_mensaje
        FOREIGN KEY (id_mensaje)
        REFERENCES Mensaje(id_mensaje)
        ON DELETE CASCADE,

    CONSTRAINT fk_respuesta_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE CASCADE
);

-- ============================================================
-- 18. NOTIFICACION
-- ============================================================

CREATE TABLE Notificacion (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    mensaje TEXT NOT NULL,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario INTEGER NOT NULL,
    id_taller INTEGER NULL,

    CONSTRAINT fk_notificacion_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES Usuario(id_usuario)
        ON DELETE CASCADE,

    CONSTRAINT fk_notificacion_taller
        FOREIGN KEY (id_taller)
        REFERENCES Taller(id_taller)
        ON DELETE SET NULL
);

-- ============================================================
-- 19. NOTIFICACION LEIDA
-- ============================================================

CREATE TABLE NotificacionLeida (
    id_notificacion INTEGER NOT NULL,
    id_alumno INTEGER NOT NULL,
    fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notificacion_leida
        PRIMARY KEY (id_notificacion, id_alumno),

    CONSTRAINT fk_notificacion_leida_notificacion
        FOREIGN KEY (id_notificacion)
        REFERENCES Notificacion(id_notificacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_notificacion_leida_alumno
        FOREIGN KEY (id_alumno)
        REFERENCES Alumno(id_usuario)
        ON DELETE CASCADE
);

-- ============================================================
-- 20. REGLA DIPLOMA
-- ============================================================

CREATE TABLE ReglaDiploma (
    id_regla_diploma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_nivel VARCHAR(100) NOT NULL,
    porcentaje_minimo NUMERIC(5,2) NOT NULL,
    porcentaje_maximo NUMERIC(5,2) NOT NULL,
    descripcion VARCHAR(300),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    color VARCHAR(20) NOT NULL,
    icono VARCHAR(120) NOT NULL,

    CONSTRAINT chk_regla_diploma_porcentaje
        CHECK (
            porcentaje_minimo BETWEEN 0 AND 100
            AND porcentaje_maximo BETWEEN 0 AND 100
            AND porcentaje_minimo <= porcentaje_maximo
        )
);

-- ============================================================
-- 21. DIPLOMA
-- ============================================================

CREATE TABLE Diploma (
    id_diploma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_alumno INTEGER NOT NULL,
    id_taller INTEGER NOT NULL,
    id_regla_diploma INTEGER NOT NULL,

    -- Snapshot historico de la regla al momento de emitir el diploma
    nombre_nivel VARCHAR(100) NOT NULL,
    descripcion VARCHAR(300),
    porcentaje_minimo NUMERIC(5,2) NOT NULL,
    porcentaje_maximo NUMERIC(5,2) NOT NULL,
    porcentaje_obtenido NUMERIC(5,2) NOT NULL,

    fecha_emision DATE NOT NULL DEFAULT CURRENT_DATE,
    archivo_url VARCHAR(500) NULL,

    CONSTRAINT fk_diploma_alumno
        FOREIGN KEY (id_alumno)
        REFERENCES Alumno(id_usuario)
        ON DELETE RESTRICT,

    CONSTRAINT fk_diploma_taller
        FOREIGN KEY (id_taller)
        REFERENCES Taller(id_taller)
        ON DELETE RESTRICT,

    CONSTRAINT fk_diploma_regla
        FOREIGN KEY (id_regla_diploma)
        REFERENCES ReglaDiploma(id_regla_diploma)
        ON DELETE RESTRICT,

    CONSTRAINT chk_diploma_porcentaje
        CHECK (porcentaje_obtenido BETWEEN 0 AND 100),

    CONSTRAINT uq_diploma_alumno_taller
        UNIQUE (id_alumno, id_taller)
);

-- ============================================================
-- 22. REGLA RECONOCIMIENTO
-- ============================================================

CREATE TABLE ReglaReconocimiento (
    id_regla INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(120) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    umbral INTEGER NOT NULL,
    motivo VARCHAR(200),
    color VARCHAR(20) NOT NULL,
    imagen_url VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_regla_reconocimiento_tipo
        CHECK (tipo IN ('ASISTENCIA_ACUMULADA', 'TALLER_COMPLETADO')),

    CONSTRAINT chk_regla_reconocimiento_umbral
        CHECK (
            (tipo = 'ASISTENCIA_ACUMULADA' AND umbral > 0)
            OR
            (tipo = 'TALLER_COMPLETADO' AND umbral = 100)
        )
);

-- ============================================================
-- 23. RECONOCIMIENTO
-- ============================================================

CREATE TABLE Reconocimiento (
    id_reconocimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_alumno INTEGER NOT NULL,
    id_regla INTEGER NOT NULL,
    id_taller INTEGER NULL,
    fecha_emision DATE NOT NULL DEFAULT CURRENT_DATE,
    archivo_url VARCHAR(500) NULL,

    CONSTRAINT fk_reconocimiento_alumno
        FOREIGN KEY (id_alumno)
        REFERENCES Alumno(id_usuario)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reconocimiento_regla
        FOREIGN KEY (id_regla)
        REFERENCES ReglaReconocimiento(id_regla)
        ON DELETE RESTRICT,

    CONSTRAINT fk_reconocimiento_taller
        FOREIGN KEY (id_taller)
        REFERENCES Taller(id_taller)
        ON DELETE RESTRICT
);

-- ============================================================
-- INDICES
-- ============================================================

CREATE INDEX idx_detalle_carga_id_carga
    ON DetalleCargaAlumno(id_carga);

CREATE INDEX idx_detalle_carga_id_usuario
    ON DetalleCargaAlumno(id_usuario);

CREATE INDEX idx_taller_id_docente
    ON Taller(id_docente);

CREATE INDEX idx_taller_id_tipo
    ON Taller(id_tipo);

CREATE INDEX idx_taller_id_area
    ON Taller(id_area);

CREATE INDEX idx_sesion_id_taller
    ON Sesion(id_taller);

CREATE INDEX idx_recurso_id_sesion
    ON Recurso(id_sesion);

CREATE INDEX idx_inscripcion_id_alumno
    ON Inscripcion(id_alumno);

CREATE INDEX idx_inscripcion_id_taller
    ON Inscripcion(id_taller);

CREATE INDEX idx_asistencia_id_inscripcion
    ON Asistencia(id_inscripcion);

CREATE INDEX idx_asistencia_id_sesion
    ON Asistencia(id_sesion);

CREATE INDEX idx_notificacion_id_taller
    ON Notificacion(id_taller);

CREATE INDEX idx_mensaje_id_alumno
    ON Mensaje(id_alumno);

CREATE INDEX idx_mensaje_id_usuario
    ON Mensaje(id_usuario);

CREATE INDEX idx_mensaje_id_taller
    ON Mensaje(id_taller);

CREATE INDEX idx_diploma_id_alumno
    ON Diploma(id_alumno);

CREATE INDEX idx_diploma_id_taller
    ON Diploma(id_taller);

CREATE INDEX idx_reconocimiento_id_alumno
    ON Reconocimiento(id_alumno);

CREATE INDEX idx_reconocimiento_id_regla
    ON Reconocimiento(id_regla);

CREATE INDEX idx_reconocimiento_id_taller
    ON Reconocimiento(id_taller);

-- ============================================================
-- INDICES UNICOS PARA RECONOCIMIENTOS
-- ============================================================

CREATE UNIQUE INDEX uq_reconocimiento_asistencia
    ON Reconocimiento(id_alumno, id_regla)
    WHERE id_taller IS NULL;

CREATE UNIQUE INDEX uq_reconocimiento_taller
    ON Reconocimiento(id_alumno, id_regla, id_taller)
    WHERE id_taller IS NOT NULL;

-- ============================================================
-- FUNCION: FECHA DE MODIFICACION DE USUARIO
-- ============================================================

CREATE OR REPLACE FUNCTION fn_actualizar_fecha_modificacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_modificacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_usuario_fecha_modificacion
BEFORE UPDATE ON Usuario
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_fecha_modificacion();

-- ============================================================
-- FUNCION: VALIDAR CANTIDAD MAXIMA DE SESIONES
-- Sesion: maximo 3
-- Seminario: maximo 1
-- ============================================================

CREATE OR REPLACE FUNCTION fn_validar_cantidad_sesiones()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_tipo VARCHAR(50);
    v_taller INTEGER;
    v_cantidad INTEGER;
BEGIN
    v_taller := COALESCE(NEW.id_taller, OLD.id_taller);

    SELECT te.nombre
    INTO v_tipo
    FROM Taller t
    INNER JOIN TipoEvento te
        ON te.id_tipo = t.id_tipo
    WHERE t.id_taller = v_taller;

    SELECT COUNT(*)
    INTO v_cantidad
    FROM Sesion
    WHERE id_taller = v_taller;

    IF LOWER(v_tipo) IN ('sesion', 'sesión') AND v_cantidad > 3 THEN
        RAISE EXCEPTION
            'Un taller de tipo Sesión no puede tener más de 3 sesiones.';
    ELSIF LOWER(v_tipo) = 'seminario' AND v_cantidad > 1 THEN
        RAISE EXCEPTION
            'Un Seminario solo puede tener 1 sesión.';
    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_validar_cantidad_sesiones
AFTER INSERT OR UPDATE OR DELETE ON Sesion
FOR EACH ROW
EXECUTE FUNCTION fn_validar_cantidad_sesiones();

-- ============================================================
-- FUNCION: PROCESAR ASISTENCIA
-- ============================================================

CREATE OR REPLACE FUNCTION fn_procesar_asistencia()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_id_inscripcion INTEGER;
    v_id_alumno INTEGER;
    v_id_taller INTEGER;

    v_total_sesiones INTEGER;
    v_total_registradas INTEGER;
    v_total_asistidas INTEGER;

    v_porcentaje NUMERIC(5,2);
    v_total_asistencias_alumno INTEGER;

    r RECORD;
BEGIN
    v_id_inscripcion := COALESCE(NEW.id_inscripcion, OLD.id_inscripcion);

    SELECT i.id_alumno, i.id_taller
    INTO v_id_alumno, v_id_taller
    FROM Inscripcion i
    WHERE i.id_inscripcion = v_id_inscripcion;

    -- ========================================================
    -- ASISTENCIAS ACUMULADAS DEL ALUMNO
    -- ========================================================

    SELECT COUNT(*)
    INTO v_total_asistencias_alumno
    FROM Asistencia a
    INNER JOIN Inscripcion i
        ON i.id_inscripcion = a.id_inscripcion
    WHERE i.id_alumno = v_id_alumno
      AND a.asistio = TRUE;

    FOR r IN
        SELECT *
        FROM ReglaReconocimiento rr
        WHERE rr.activo = TRUE
          AND rr.tipo = 'ASISTENCIA_ACUMULADA'
          AND rr.umbral <= v_total_asistencias_alumno
    LOOP
        INSERT INTO Reconocimiento (
            id_alumno,
            id_regla,
            id_taller,
            fecha_emision
        )
        VALUES (
            v_id_alumno,
            r.id_regla,
            NULL,
            CURRENT_DATE
        )
        ON CONFLICT DO NOTHING;
    END LOOP;

    -- ========================================================
    -- SESIONES DEL TALLER
    -- ========================================================

    SELECT COUNT(*)
    INTO v_total_sesiones
    FROM Sesion s
    WHERE s.id_taller = v_id_taller;

    IF v_total_sesiones = 0 THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    -- ========================================================
    -- SESIONES REGISTRADAS PARA LA INSCRIPCION
    -- ========================================================

    SELECT
        COUNT(*),
        COUNT(*) FILTER (WHERE a.asistio = TRUE)
    INTO
        v_total_registradas,
        v_total_asistidas
    FROM Asistencia a
    INNER JOIN Sesion s
        ON s.id_sesion = a.id_sesion
    WHERE a.id_inscripcion = v_id_inscripcion
      AND s.id_taller = v_id_taller;

    IF v_total_registradas = v_total_sesiones THEN

        v_porcentaje := ROUND(
            (v_total_asistidas::NUMERIC / v_total_sesiones::NUMERIC) * 100,
            2
        );

        -- ====================================================
        -- DIPLOMA SEGUN REGLA
        -- ====================================================

        SELECT *
        INTO r
        FROM ReglaDiploma rd
        WHERE rd.activo = TRUE
          AND v_porcentaje BETWEEN
              rd.porcentaje_minimo
              AND rd.porcentaje_maximo
        ORDER BY rd.porcentaje_minimo DESC
        LIMIT 1;

        IF FOUND THEN
            INSERT INTO Diploma (
                id_alumno,
                id_taller,
                id_regla_diploma,
                nombre_nivel,
                descripcion,
                porcentaje_minimo,
                porcentaje_maximo,
                porcentaje_obtenido,
                fecha_emision
            )
            VALUES (
                v_id_alumno,
                v_id_taller,
                r.id_regla_diploma,
                r.nombre_nivel,
                r.descripcion,
                r.porcentaje_minimo,
                r.porcentaje_maximo,
                v_porcentaje,
                CURRENT_DATE
            )
            ON CONFLICT (id_alumno, id_taller)
            DO NOTHING;
        END IF;

        -- ====================================================
        -- RECONOCIMIENTO POR 100% DEL TALLER
        -- ====================================================

        IF v_porcentaje = 100 THEN
            FOR r IN
                SELECT *
                FROM ReglaReconocimiento rr
                WHERE rr.activo = TRUE
                  AND rr.tipo = 'TALLER_COMPLETADO'
                  AND rr.umbral = 100
            LOOP
                INSERT INTO Reconocimiento (
                    id_alumno,
                    id_regla,
                    id_taller,
                    fecha_emision
                )
                VALUES (
                    v_id_alumno,
                    r.id_regla,
                    v_id_taller,
                    CURRENT_DATE
                )
                ON CONFLICT DO NOTHING;
            END LOOP;
        END IF;

    END IF;

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_procesar_asistencia
AFTER INSERT OR UPDATE OR DELETE ON Asistencia
FOR EACH ROW
EXECUTE FUNCTION fn_procesar_asistencia();

-- ============================================================
-- FUNCION: MARCAR MENSAJE COMO RESPONDIDO
-- ============================================================

CREATE OR REPLACE FUNCTION fn_marcar_mensaje_respondido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE Mensaje
    SET respondido = TRUE
    WHERE id_mensaje = NEW.id_mensaje;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_mensaje_respondido
AFTER INSERT ON RespuestaMensaje
FOR EACH ROW
EXECUTE FUNCTION fn_marcar_mensaje_respondido();

-- ============================================================
-- DATOS INICIALES: TIPOS DE EVENTO
-- ============================================================

INSERT INTO TipoEvento (nombre)
VALUES
    ('Sesión'),
    ('Seminario')
ON CONFLICT (nombre) DO NOTHING;

-- ============================================================
-- DATOS INICIALES: AREAS
-- ============================================================

INSERT INTO TipoArea (nombre)
VALUES
    ('Matemática'),
    ('Ciencias'),
    ('Comunicación'),
    ('Ciencias Sociales'),
    ('Informática'),
    ('Humanidades')
ON CONFLICT (nombre) DO NOTHING;

-- ============================================================
-- DATOS INICIALES: REGLAS DE RECONOCIMIENTO
-- ============================================================

INSERT INTO ReglaReconocimiento
    (titulo, tipo, umbral, motivo, color, imagen_url, activo)
VALUES
    (
        'Primera asistencia',
        'ASISTENCIA_ACUMULADA',
        1,
        'Primera asistencia registrada',
        'success',
        NULL,
        TRUE
    ),
    (
        '5 asistencias',
        'ASISTENCIA_ACUMULADA',
        5,
        'Ha alcanzado 5 asistencias acumuladas',
        'primary',
        NULL,
        TRUE
    ),
    (
        '10 asistencias',
        'ASISTENCIA_ACUMULADA',
        10,
        'Ha alcanzado 10 asistencias acumuladas',
        'info',
        NULL,
        TRUE
    ),
    (
        '20 asistencias',
        'ASISTENCIA_ACUMULADA',
        20,
        'Ha alcanzado 20 asistencias acumuladas',
        'warning',
        NULL,
        TRUE
    ),
    (
        'Taller completado',
        'TALLER_COMPLETADO',
        100,
        'Completó el taller con 100% de asistencia',
        'success',
        NULL,
        TRUE
    );

-- ============================================================
-- NOTA SOBRE REGLAS DE DIPLOMA
-- ============================================================
-- Los cuatro niveles definidos son:
--   1. Excelencia
--   2. Aprobación
--   3. Participación
--   4. Sin registro
--
-- Los porcentajes exactos se insertan según los valores finales
-- definidos por el proyecto. No se inventan aquí.
-- ============================================================